using Rowbot.Extractors.Framework;

namespace Rowbot;

/// <summary>
/// <para>
/// Connector that supports querying data.
/// </para>
/// </summary>
/// <typeparam name="TInput">Data type of previous extract or transform block</typeparam>
/// <typeparam name="TOutput">Data type to extract</typeparam>
public interface IReadConnector<TInput, TOutput>
{
    /// <summary>
    /// Performs a query operation on a data source.
    /// </summary>
    /// <param name="parameters">Extract parameters generated by <see cref="ExtractContext{TInput}"/></param>
    /// <returns>Returned result set</returns>
    Task<IEnumerable<TOutput>> QueryAsync(ExtractParameter[] parameters);
}